### ISSUE TITLE
FEAT_PMUv3

### ISSUE THREAD

**Issue by cyring** [lelegard/arm-cpusysregs#2]
Based on this [output](https://github.com/lelegard/arm-cpusysregs/discussions/1#discussioncomment-7932768) PMU version differs between these two levels:
```
sysregs -s|grep FEAT_PMUv3
FEAT_PMUv3 ............... yes
FEAT_PMUv3_EDGE .......... no
FEAT_PMUv3_ICNTR ......... no
FEAT_PMUv3_SS ............ no
FEAT_PMUv3_TH ............ no
FEAT_PMUv3p1 ............. yes
FEAT_PMUv3p4 ............. no
FEAT_PMUv3p5 ............. no
FEAT_PMUv3p7 ............. no
FEAT_PMUv3p8 ............. no
FEAT_PMUv3p9 ............. no
```
```
sysregs -S|grep FEAT_PMUv3
FEAT_PMUv3 ............... no
FEAT_PMUv3_EDGE .......... no
FEAT_PMUv3_ICNTR ......... no
FEAT_PMUv3_SS ............ no
FEAT_PMUv3_TH ............ no
FEAT_PMUv3p1 ............. no
FEAT_PMUv3p4 ............. no
FEAT_PMUv3p5 ............. no
FEAT_PMUv3p7 ............. no
FEAT_PMUv3p8 ............. no
FEAT_PMUv3p9 ............. no
```

I'm aware of:
> -S : same as -s but read registers at EL0 (maybe partial, may fail)

... and hope it will help.

**Comment by lelegard** [comment]
Hi @cyring,

Thanks for reporting this. It seems expected. As you mentioned, in the `-S` case, the registers are read at EL0. The PMU version is in register `ID_AA64DFR0_EL1` which can be read at EL1 only.

As [explained here](https://www.kernel.org/doc/html/latest/arch/arm64/cpu-feature-registers.html), the Linux kernel intercepts the "illegal instruction" trap resulting from reading an EL1 register from EL0 and returns the register value. However, for "security" reasons, some fields of the registers are "masked out". The article says:

> Applications should only be able to receive information that is relevant to the normal operation in userspace. Hence, some of the fields are masked out (i.e, made invisible) and their values are set to indicate the feature is 'not supported'.

So, I assume that the kernel considers that the Arm performance monitoring features are not suitable for usage in userland.

**Comment by cyring** [comment]
Thank you for pointing this reading.
